api/urls.py
from django.urls import path
from .views import todos_view


app_name="api"
urlpatterns = [
    path('todos/',todos_view,name='todos')
]

prima_app/urls.py
from django.urls import path
from prima_app.views import homepage
from prima_app.views import welcome
from prima_app.views import lista,chi_siamo,variabili,index
from primo_progetto.views import index_root


app_name="prima_app"
urlpatterns=[
    path('prima_app/index',index,name='index'),
    path('prima_app/homepage',homepage,name='homepage'),
    path('prima_app/welcome',welcome,name='welcome'),
    path('prima_app/lista',lista,name='lista'),
    path('prima_app/chi_siamo',chi_siamo,name='chi_siamo'),
    path('prima_app/variabili',variabili,name='variabili'),
    path('prima_app/index_root',index_root,name='index_root'),
    
]

primo_progetto/urls.py
from django.contrib import admin
from django.urls import path,include
from primo_progetto.views import index_root

app_name="primo_progetto"
urlpatterns = [
    path('admin/', admin.site.urls),
    path("",index_root,name='index_root'),
    path('',include("prima_app.urls",namespace="prima_app")),
    path('',include("seconda_app.urls",namespace="seconda_app")),
    path('',include("news.urls",namespace="news")),
    path('',include("voti.urls",namespace="voti")),
    path('',include("eventi.urls",namespace="eventi")),
    path('',include("eventi_culturali.urls",namespace="eventi_culturali")),
    path('accounts/', include('django.contrib.auth.urls')),
    path('',include("forms_app.urls",namespace="forms_app")),
    path('',include("api.urls",namespace="api")),


]

prima_app/views.py
from django.shortcuts import render

# Create your views here.

def homepage(request):
    return render(request,"prima_app/homepage.html")

def welcome(request):
    return render(request,"prima_app/welcome.html")

def lista(request):
    return render(request,"prima_app/lista.html")

def chi_siamo(request):
    return render(request,"prima_app/chi_siamo.html")

def variabili(request):
    context={
        'var1':'Prima variabile',
        'var2':'Seconda variabile',
        'var3':'Terza variabile',
    }
    return render(request,"variabili.html",context)

def index(request):
    return render(request,"prima_app/index.html")

prima_app/templates/prima_app/chi_siamo.html
{% extends 'primo_progetto/base.html' %}

{%block title%} {{block.super}} | Chi siamo {%endblock title%}

    {%block content%}
    <h1>Chi siamo</h1>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque eget nisl dapibus, vestibulum nibh vel, congue magna. Etiam at ipsum et purus mattis pulvinar in in justo. Donec suscipit tincidunt scelerisque. Nunc finibus, ipsum et sollicitudin gravida, nisi ipsum venenatis eros, at consequat justo nisi et tellus. Aliquam pretium libero nec elit fringilla hendrerit. Quisque rutrum semper sem, a volutpat enim blandit vel. Sed ornare vel libero at tristique. Proin vel feugiat orci. Lorem ipsum dolor sit amet, consectetur adipiscing elit.

        Vestibulum volutpat mi magna, quis mollis augue blandit et. Etiam ac bibendum ex, at consequat ex. Vivamus scelerisque, magna iaculis consectetur aliquet, sem ex fringilla ipsum, ac aliquam eros ex sit amet ipsum. Etiam egestas egestas dolor, sed fringilla risus viverra sed. Curabitur in porta tellus. Etiam laoreet augue non nisl dignissim feugiat. Quisque erat erat, imperdiet id quam id, dictum vestibulum nisi. Suspendisse in quam tellus. Vestibulum nisi turpis, volutpat a pretium ut, rutrum sed mi. Pellentesque sit amet lorem convallis, aliquet arcu sed, hendrerit massa. Vivamus nisl tortor, pellentesque a tellus id, semper dapibus nisi. Mauris elementum id tellus eget euismod. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Sed maximus leo in ligula fringilla ornare.
        
        Quisque vitae ligula finibus, tempus turpis vel, euismod odio. Nunc vel lacus sem. Etiam eu consectetur ligula, a maximus nulla. Quisque faucibus porttitor lectus sed aliquet. Nam non mollis odio, sed eleifend nunc. Vestibulum sagittis malesuada mauris eu commodo. Nunc laoreet facilisis augue ut tincidunt.
        
        Curabitur gravida nunc vel mollis aliquam. Donec non eros maximus, finibus diam id, pretium metus. Proin sed efficitur orci, placerat euismod eros. Integer tristique, ligula eu tempus egestas, magna est luctus metus, quis feugiat urna metus at ex. Donec libero tortor, condimentum eget sodales non, ultricies non turpis. Nam sed lorem ut elit dictum viverra tempus non eros. Morbi dignissim at augue condimentum gravida.
        
        Nam commodo consectetur aliquam. Cras venenatis sollicitudin magna, nec pulvinar tortor dictum in. In non mattis nisl. Fusce molestie consectetur commodo. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Maecenas eu scelerisque lacus, id porta nulla. Donec elit mi, commodo a tempus vitae, venenatis in tortor. Praesent dignissim lectus convallis, sodales ex eget, venenatis sem. In et condimentum nulla.</p>
    {%endblock content%}

prima_app/templates/prima_app/homepage.html
{% extends 'primo_progetto/base.html' %}

    {%block title%} {{block.super}} | Homepage {%endblock title%}

    {%block content%}
    <h1>Benvenuto</h1>
    {%endblock content%}

prima_app/templates/prima_app/index.html
{% extends 'primo_progetto/base.html' %}

    {%block title%} {{block.super}} | Index {%endblock title%}

    
        {%block content%}    
        <ol>                   
            <li><a href="{% url 'prima_app:index_root'%}">Index root</a></li>
            <li><a href="{% url 'prima_app:homepage'%}">Home page benvenuto</a></li>
            <li><a href="{% url 'prima_app:welcome'%}">Welcome</a></li>
            <li><a href="{% url 'prima_app:lista'%}">Lista</a></li>
            <li><a href="{% url 'prima_app:chi_siamo'%}">Chi siamo</a></li>
            <li><a href="{% url 'prima_app:variabili'%}">Variabili</a></li>
        </ol>
        {%endblock content%}
      


    

prima_app/templates/prima_app/lista.html
{% extends 'primo_progetto/base.html' %}

    {%block title%} {{block.super}} | Lista {%endblock title%}

    {%block content%}
        <ol>Primo</ol>
        <ol>Secondo</ol>
        <ol>Terzo</ol>
    {%endblock content%}

prima_app/templates/prima_app/variabili.html
{% extends 'primo_progetto/base.html' %}

{%block title%} {{block.super}} | Variabili {%endblock title%}

{%block content%}
    <ol>
        <h1>VARIABILI</h1>
        <li>{{var1}}</li>
        <li>{{var2}}</li>
        <li>{{var3}}</li>
    </ol>
{%endblock content%}

prima_app/templates/prima_app/welcome.html
{% extends 'primo_progetto/base.html' %}

    {%block title%} {{block.super}} | Welcome {%endblock title%}

    {%block content%}
    <h1>Welcome to the page! </h1>
    {%endblock content%}