api/urls.py
from django.urls import path
from .views import todos_view


app_name="api"
urlpatterns = [
    path('todos/',todos_view,name='todos')
]

eventi/urls.py
from django.urls import path 
from .views import vieweventi_a,vieweventi_b,vieweventi_c,vieweventi_d,indexEventi

app_name="eventi"

urlpatterns = [
    path("eventi/vieweventi_a",vieweventi_a,name="vieweventi_a"),
    path("eventi/vieweventi_b",vieweventi_b,name="vieweventi_b"),
     path("eventi/vieweventi_c",vieweventi_c,name="vieweventi_c"),
     path("eventi/vieweventi_d",vieweventi_d,name="vieweventi_d"),
     path("eventi/",indexEventi,name="indexEventi")
    
]

forms_app/urls.py
from django.urls import path 
from .views import contatti,lista_contatti,elimina_contatto,modifica_contatto

app_name="forms_app"

urlpatterns = [
    path("contattaci/",contatti,name="contatti"),
    path("contattaci/lista_contatti",lista_contatti,name="lista_contatti"),
    path("contattaci/elimina_contatto/<int:pk>",elimina_contatto,name="elimina_contatto"),
    path("contattaci/modifica_contatto/<int:pk>",modifica_contatto,name="modifica_contatto"),


]

news/urls.py
from django.urls import path 
from .views import home,index_news,articoloDetailViewCB,listaArticoli,queryBase,giornalistaDetailView

app_name="news"

urlpatterns = [
    path("news/",home,name="home"),
    path("news/articoli/<int:pk>",articoloDetailViewCB.as_view(),name="articolo_detail"),
    path("news/lista_articoli_giornalista/<int:pk>",listaArticoli,name="listaArticoli"),
    path("news/lista_articoli_giornalista/",listaArticoli,name="listaArticoli"),
    path("news/query_base/",queryBase,name="query_base"),
    path("news/lista_articoli_giornalista/<int:pk>",giornalistaDetailView,name="giornalista_detail"),
    path("news/index_news/",index_news,name="index_news")
]

primo_progetto/urls.py
from django.contrib import admin
from django.urls import path,include
from primo_progetto.views import index_root

app_name="primo_progetto"
urlpatterns = [
    path('admin/', admin.site.urls),
    path("",index_root,name='index_root'),
    path('',include("prima_app.urls",namespace="prima_app")),
    path('',include("seconda_app.urls",namespace="seconda_app")),
    path('',include("news.urls",namespace="news")),
    path('',include("voti.urls",namespace="voti")),
    path('',include("eventi.urls",namespace="eventi")),
    path('',include("eventi_culturali.urls",namespace="eventi_culturali")),
    path('accounts/', include('django.contrib.auth.urls')),
    path('',include("forms_app.urls",namespace="forms_app")),
    path('',include("api.urls",namespace="api")),


]

voti/urls.py
from django.urls import path
from voti.views import view_a,view_b,view_c,index_voti,view_d



app_name="voti"

urlpatterns=[
    path("voti/",index_voti,name="index_voti"),
    path("voti/view_a",view_a,name="view_a"),
    path("voti/view_b",view_b,name="view_b"),
    path("voti/view_c",view_c,name="view_c"),
    path("voti/view_d",view_d,name="view_d"),
]

primo_progetto/views.py
from django.shortcuts import render


def index_root(request):
    return render(request,"primo_progetto/index_root.html")

primo_progetto/templates/primo_progetto/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
    <title>{% block title %} My project {% endblock title %}</title>
  </head>
  <body>
    
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
        <a class="navbar-brand" href="{% url 'index_root'%}">Primo progetto</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Prima app
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="{% url 'prima_app:index'%}">Index</a>
                    <a class="dropdown-item" href="{% url 'prima_app:homepage'%}">Home</a>
                    <a class="dropdown-item" href="{% url 'prima_app:chi_siamo'%}">Chi siamo</a>
                    <a class="dropdown-item" href="{% url 'prima_app:variabili'%}">Variabili</a>
              </div>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Seconda app
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <a class="dropdown-item" href="{% url 'seconda_app:index_seconda_app'%}">Index</a>
                      <a class="dropdown-item" href="{% url 'seconda_app:es_if'%}">If</a>
                      <a class="dropdown-item" href="{% url 'seconda_app:if_else_elif'%}">If-Else-Elif</a>
                      <a class="dropdown-item" href="{% url 'seconda_app:es_for'%}">For</a>
                      
                </div>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  News
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                      <a class="dropdown-item" href="{% url 'news:index_news'%}">Index</a>
                      <a class="dropdown-item" href="{% url 'news:home'%}">Homepage</a>
                      <a class="dropdown-item" href="{% url 'news:listaArticoli'%}">Articolo Lista</a>
                      <a class="dropdown-item" href="{% url 'news:query_base'%}">Query Base</a>
                </div>
              </li>

              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Voti
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <a class="dropdown-item" href="{% url 'voti:index_voti'%}">Index</a>
                      <a class="dropdown-item" href="{% url 'voti:view_a'%}">View A</a>
                      <a class="dropdown-item" href="{% url 'voti:view_b'%}">View B</a>
                      <a class="dropdown-item" href="{% url 'voti:view_c'%}">View C</a>
                      <a class="dropdown-item" href="{% url 'voti:view_d'%}">View D</a>
                      
                </div>
              </li>

              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Eventi
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <a class="dropdown-item" href="{% url 'eventi:indexEventi'%}">Index</a>
                      <a class="dropdown-item" href="{% url 'eventi:vieweventi_a'%}">View A</a>
                      <a class="dropdown-item" href="{% url 'eventi:vieweventi_b'%}">View B</a>
                      <a class="dropdown-item" href="{% url 'eventi:vieweventi_c'%}">View C</a>
                      <a class="dropdown-item" href="{% url 'eventi:vieweventi_d'%}">View D</a>
                      
                </div>
              </li>



              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Eventi culturali
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <a class="dropdown-item" href="{% url 'eventi_culturali:index_eventi_culturali'%}">Index</a>
                      <a class="dropdown-item" href="{% url 'eventi_culturali:vieweventi_culturali_a'%}">View A</a>
                      <a class="dropdown-item" href="{% url 'eventi_culturali:vieweventi_culturali_b'%}">View B</a>
                      <a class="dropdown-item" href="{% url 'eventi_culturali:vieweventi_culturali_c'%}">View C</a>
                      <a class="dropdown-item" href="{% url 'eventi_culturali:vieweventi_culturali_d'%}">View D</a>
                      <a class="dropdown-item" href="{% url 'eventi_culturali:vieweventi_culturali_e'%}">View E</a>
                      <a class="dropdown-item" href="{% url 'eventi_culturali:vieweventi_culturali_f'%}">View F</a>

                      
                </div>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Contatti
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <a class="dropdown-item" href="{% url 'forms_app:contatti'%}">Contattaci</a>
                  <a class="dropdown-item" href="{% url 'forms_app:lista_contatti'%}">Lista contatti</a>

                      
                </div>
              </li>



        </div>
        {% if request.user.is_authenticated %}
          <li class ="nav-item dropdown">
            <a class ="dropdown-item" href="#" id="navbarDropdown" role ="button"
            data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            {{request.user.username}}
          </a>
          <div class ="dropdown-menu" aria-lebelledby="navbarDropdown" >
            <div class ="dropdown-divider"></div>
            <form id="logout-form" action="{% url 'logout' %}"method="post">
            {% csrf_token %}
              <button class="btn ft-power" type="submit">Logout</button>
            </form>
          </div>
        </li>
        {% else %}
  
          <li class="nav-item">
            <a class="dropdown-item"  href="{% url 'login'%}">Login </a>

          </li>
          {% endif %}
      </nav>
     



      
      <div style="margin-left:50px">

        {%block content%}

        {%endblock content%}
      </div>
    

      

      









    
    
      <!-- Optional JavaScript; choose one of the two! -->

    
      <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>

    <!-- Option 2: jQuery, Popper.js, and Bootstrap JS
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
    -->
  </body>
</html>

primo_progetto/templates/primo_progetto/index_root.html
{% extends 'primo_progetto/base.html' %}
    <title>Index root</title>
    
    {%block content%}
    <h5>PRIMO PROGETTO - ROOT MENU'</h5>
    <ol>
        <li><a href="/admin">Pannello admin</a></li>
        <li><a href="{% url 'prima_app:index'%}"> Index prima app</a></li>
        <li><a href="{% url 'seconda_app:index_seconda_app'%}"> Index seconda app </a></li>
        <li><a href="{% url 'news:index_news'%}"> Index news </a></li>
        <li><a href="{% url 'voti:index_voti'%}"> Index voti </a></li>
        
    </ol>

    {%endblock content%}