api/urls.py
from django.urls import path
from .views import todos_view


app_name="api"
urlpatterns = [
    path('todos/',todos_view,name='todos')
]

eventi_culturali/urls.py
from django.urls import path 
from .views import indexEventiCulturali,vieweventi_culturali_a,vieweventi_culturali_b,vieweventi_culturali_c,vieweventi_culturali_d,vieweventi_culturali_e,vieweventi_culturali_f

app_name="eventi_culturali"

urlpatterns = [
    
    path("eventi_culturali/vieweventi_culturali_a",vieweventi_culturali_a,name="vieweventi_culturali_a"),
    path("eventi_culturali/vieweventi_culturali_b",vieweventi_culturali_b,name="vieweventi_culturali_b"),
     path("eventi_culturali/vieweventi_culturali_c",vieweventi_culturali_c,name="vieweventi_culturali_c"),
     path("eventi_culturali/vieweventi_culturali_d",vieweventi_culturali_d,name="vieweventi_culturali_d"),
     path("eventi_culturali/vieweventi_culturali_e",vieweventi_culturali_e,name="vieweventi_culturali_e"),
     path("eventi_culturali/vieweventi_culturali_f",vieweventi_culturali_f,name="vieweventi_culturali_f"),
     path("eventi_culturali/",indexEventiCulturali,name="index_eventi_culturali")
    
]

primo_progetto/urls.py
from django.contrib import admin
from django.urls import path,include
from primo_progetto.views import index_root

app_name="primo_progetto"
urlpatterns = [
    path('admin/', admin.site.urls),
    path("",index_root,name='index_root'),
    path('',include("prima_app.urls",namespace="prima_app")),
    path('',include("seconda_app.urls",namespace="seconda_app")),
    path('',include("news.urls",namespace="news")),
    path('',include("voti.urls",namespace="voti")),
    path('',include("eventi.urls",namespace="eventi")),
    path('',include("eventi_culturali.urls",namespace="eventi_culturali")),
    path('accounts/', include('django.contrib.auth.urls')),
    path('',include("forms_app.urls",namespace="forms_app")),
    path('',include("api.urls",namespace="api")),


]

eventi_culturali/models.py
from django.db import models


class Evento(models.Model):

    titolo = models.CharField(max_length=50)
    descrizione  = models.TextField()
    data_inizio = models.DateField(blank=True,null=True)
    data_fine = models.DateField(blank=True,null=True) 
    posti_disponibili=models.IntegerField(default=0,blank=True)

    def __str__(self):
        return self.titolo + " "+ self.descrizione 
    
    
    class Meta:
        verbose_name= "Evento"
        verbose_name_plural="Eventi"

# Create your models here.

eventi_culturali/views.py
from django.shortcuts import render
from .models import Evento
import datetime

def indexEventiCulturali(request):
    return render(request,"index_eventi_culturali.html")

def vieweventi_culturali_a(request):
    eventiCulturali=Evento.objects.order_by('data_inizio')
    context={
        'eventiCulturali':eventiCulturali
    }
    
    return render(request,"vieweventi_culturali_a.html",context)

def vieweventi_culturali_b(request):
    eventiCulturali=Evento.objects.all()
    context={
        'eventiCulturali':eventiCulturali
    }
    
    return render(request,"vieweventi_culturali_b.html",context)
   
def vieweventi_culturali_c(request):
    
    eventiCulturali=Evento.objects.filter(data_inizio__gt=datetime.date(2025,6,11))

    context={
        'eventiCulturali':eventiCulturali
    }
    
    return render(request,"vieweventi_culturali_c.html",context)

def vieweventi_culturali_d(request):
    eventiCulturali=Evento.objects.filter(posti_disponibili__lt=80)
    context={
        'eventiCulturali':eventiCulturali
    }
    return render(request,"vieweventi_culturali_d.html",context)

def vieweventi_culturali_e(request):
    eventiCulturali=Evento.objects.filter(data_fine__lt=datetime.date(2025,5,31))
    
    context={
        'eventiCulturali':eventiCulturali
    }
    return render(request,"vieweventi_culturali_e.html",context)

def vieweventi_culturali_f(request):
    eventoMaggiorNumero=Evento.objects.order_by('-posti_disponibili').first()
    eventoMinorNumero=Evento.objects.order_by('posti_disponibili').first()


    eventiTotale=Evento.objects.all()
    NumeroTotaleDiPosti=0
    for singoloEvento in eventiTotale:
        NumeroTotaleDiPosti+=singoloEvento.posti_disponibili


    context={
            'eventoMaggiorNumero':eventoMaggiorNumero,
            'eventoMinorNumero':eventoMinorNumero,
            'NumeroTotaleDiPosti':NumeroTotaleDiPosti
        }


    return render(request,"vieweventi_culturali_f.html",context)

# Create your views here.

eventi_culturali/templates/index_eventi_culturali.html
{% extends 'primo_progetto/base.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Index Eventi Culturali </title>
</head>
<body>
                          
        {%block content%}    

        <h1>Benvenuto nella piattaforma di Eventi Culturali</h1>
        <ul>
        <li><a href="{% url 'eventi_culturali:vieweventi_culturali_a' %}">Lista degli Eventi</a></li>
        <li><a href="{% url 'eventi_culturali:vieweventi_culturali_b' %}">Dettagli degli Eventi</a></li>
        <li><a href="{% url 'eventi_culturali:vieweventi_culturali_c' %}">Eventi che iniziano dopo il 01/06/2025</a></li>
        <li><a href="{% url 'eventi_culturali:vieweventi_culturali_d' %}">Eventi con meno di 80 posti disponibili</a></li>
        <li><a href="{% url 'eventi_culturali:vieweventi_culturali_e' %}">Eventi che terminano entro il 31/05/2025</a></li>
        <li><a href="{% url 'eventi_culturali:vieweventi_culturali_f' %}">Statistiche Eventi</a></li>
        </ul>
        
        {%endblock content%}


    
</body>
</html>

eventi_culturali/templates/vieweventi_culturali_a.html
{% extends "primo_progetto/base.html" %}

{%block title%} {{block.super}} | View A {%endblock title%}

       
        {%block content%}    
            <h1>View A</h1>
            <ul>
                {% for eventoCulturale in eventiCulturali %}
                <li>Titolo: {{ eventoCulturale.titolo }} </li>
                {% endfor %}
            </ul>
        {%endblock content%}

eventi_culturali/templates/vieweventi_culturali_b.html
{% extends "primo_progetto/base.html" %}

{%block title%} {{block.super}} | View B {%endblock title%}

       
        {%block content%}    
            <h1>View B </h1>
            <ul>
                {% for eventoCulturale in eventiCulturali %}
                   <p> Titolo: {{ eventoCulturale.titolo }}
                    <br>
                    Descrizione: {{eventoCulturale.descrizione}}
                    <br>
                    Data inizio: {{eventoCulturale.data_inizio}}
                    <br>
                    Data fine: {{eventoCulturale.data_fine}}
                    <br>
                    Posti disponibili: {{eventoCulturale.posti_disponibili}}
                    <br>
                   </p>
                   --------------------------------------------
                {% endfor %}
            </ul>
        {%endblock content%}

eventi_culturali/templates/vieweventi_culturali_c.html
{% extends "primo_progetto/base.html" %}

{%block title%} {{block.super}} | View C {%endblock title%}

       
        {%block content%}    
            <h1>View C</h1>
            <ul>
                {% for eventoCulturale in eventiCulturali %}
                <li>Titolo: {{ eventoCulturale.titolo }} </li>
                {% endfor %}
            </ul>
        {%endblock content%}

eventi_culturali/templates/vieweventi_culturali_d.html
{% extends "primo_progetto/base.html" %}

{%block title%} {{block.super}} | View D {%endblock title%}

       
        {%block content%}    
            <h1>View D</h1>
            <ul>
                {% for eventoCulturale in eventiCulturali %}
                 <p> Titolo: {{ eventoCulturale.titolo }}
                    <br>
                    Descrizione: {{eventoCulturale.descrizione}}
                    <br>
                    Data inizio: {{eventoCulturale.data_inizio}}
                    <br>
                    Data fine: {{eventoCulturale.data_fine}}
                    <br>
                    Posti disponibili: {{eventoCulturale.posti_disponibili}}
                    <br>
                   </p>
                   --------------------------------------------
                {% endfor %}
            </ul>
        {%endblock content%}

eventi_culturali/templates/vieweventi_culturali_e.html
{% extends "primo_progetto/base.html" %}

{%block title%} {{block.super}} | View E {%endblock title%}

       
        {%block content%}    
            <h1>View E</h1>
            <ul>
                {% for eventoCulturale in eventiCulturali %}
                 <p> Titolo: {{ eventoCulturale.titolo }}
                    <br>
                    Descrizione: {{eventoCulturale.descrizione}}
                    <br>
                    Data inizio: {{eventoCulturale.data_inizio}}
                    <br>
                    Data fine: {{eventoCulturale.data_fine}}
                    <br>
                    Posti disponibili: {{eventoCulturale.posti_disponibili}}
                    <br>
                   </p>
                   --------------------------------------------
                {% endfor %}
            </ul>
        {%endblock content%}

eventi_culturali/templates/vieweventi_culturali_f.html
{% extends "primo_progetto/base.html" %}

{%block title%} {{block.super}} | View F {%endblock title%}

       
        {%block content%}    
            <h1>View F</h1>
            <ul>
                <h3>Evento con il maggior numero di posti disponibili. </h3>
                 <p> Titolo: {{ eventoMaggiorNumero.titolo }}
                    <br>
                    Descrizione: {{eventoMaggiorNumero.descrizione}}
                    <br>
                    Data inizio: {{eventoMaggiorNumero.data_inizio}}
                    <br>
                    Data fine: {{eventoMaggiorNumero.data_fine}}
                    <br>
                    Posti disponibili: {{eventoMaggiorNumero.posti_disponibili}}
                    <br>
                   </p>
                   --------------------------------------------
            </ul>

            <ul>
                <h3>Evento con il minor numero di posti disponibili. </h3>
                 <p> Titolo: {{ eventoMinorNumero.titolo }}
                    <br>
                    Descrizione: {{eventoMinorNumero.descrizione}}
                    <br>
                    Data inizio: {{eventoMinorNumero.data_inizio}}
                    <br>
                    Data fine: {{eventoMinorNumero.data_fine}}
                    <br>
                    Posti disponibili: {{eventoMinorNumero.posti_disponibili}}
                    <br>
                   </p>
                   --------------------------------------------
            </ul>

            <h3>Numero totale di posti disponibili per tutti gli eventi: {{NumeroTotaleDiPosti}}</h3>
            -------------------------------------------------------------------------------------------------------------------


        {%endblock content%}